kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: new
  version: '1.0'
  namespace: demoahvsjhvqw
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./new-spec.yml
  policy-sequence:
    - $ref: Project0434_Product3:Assembly-3:1
